function Proc2 = importfile(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  PROC2 = IMPORTFILE1(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  PROC2 = IMPORTFILE1(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  Proc2 = importfile1("C:\Users\marco\Documents\GitFolders\PDC2019\PDC_2019\PYTHON\Proc2.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 16-Nov-2019 21:09:08

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "VarName4", "Var5", "Var6", "Var7", "Var8", "VarName9", "Var10", "Var11", "Var12"];
opts.SelectedVariableNames = ["VarName4", "VarName9"];
opts.VariableTypes = ["string", "string", "string", "double", "string", "string", "string", "string", "double", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var5", "Var6", "Var7", "Var8", "Var10", "Var11", "Var12"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var5", "Var6", "Var7", "Var8", "Var10", "Var11", "Var12"], "EmptyFieldRule", "auto");

% Import the data
Proc2 = table2array(readtable(filename, opts));

end